version: 2
updates:
  - package-ecosystem: npm
    directory: /far
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Asia/Baku
    open-pull-requests-limit: 5
    labels:
      - dependencies
    groups:
      production-dependencies:
        dependency-type: production
      development-dependencies:
        dependency-type: development

  - package-ecosystem: cargo
    directory: /far/src-tauri
    schedule:
      interval: weekly
      day: monday
      time: "06:15"
      timezone: Asia/Baku
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - rust

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:30"
      timezone: Asia/Baku
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
